name: CI - FASTAPI

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Define the job to run on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/ --if-present

      # build
      - name: Build the application
        run: |
          echo "Building the application..."
          # Add your build commands here

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
